//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        public BankAccount()
        {
            this.LedgerAccounts = new HashSet<LedgerAccount>();
        }
    
        public int BankAccountID { get; set; }
        public string BankName { get; set; }
        public string AccountNumber { get; set; }
    
        public virtual ICollection<LedgerAccount> LedgerAccounts { get; set; }
    }
}
