//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinantialTransaction
    {
        public FinantialTransaction()
        {
            this.LedgerTransactions = new HashSet<LedgerTransaction>();
        }
    
        public long FinantialTransactionID { get; set; }
        public int SourceAccountID { get; set; }
        public int DestinationAccountID { get; set; }
        public int PaymentTypeID { get; set; }
        public int CurrencyID { get; set; }
        public decimal Amount { get; set; }
        public decimal ExchangeRate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public int CreationUserID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Description { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual LedgerAccount LedgerAccount { get; set; }
        public virtual LedgerAccount LedgerAccount1 { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<LedgerTransaction> LedgerTransactions { get; set; }
    }
}
