//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class LedgerTransaction
    {
        public LedgerTransaction()
        {
            this.LedgerTransactionDetails = new HashSet<LedgerTransactionDetail>();
        }
    
        public int LedgerTransactionID { get; set; }
        public string Description { get; set; }
        public Nullable<long> FinantialTransactionID { get; set; }
        public Nullable<int> ReservationID { get; set; }
    
        public virtual FinantialTransaction FinantialTransaction { get; set; }
        public virtual ICollection<LedgerTransactionDetail> LedgerTransactionDetails { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
