//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int NoteID { get; set; }
        public string NoteBody { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int TicketID { get; set; }
        public int CreationUserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
