//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TicketID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CreationUserID { get; set; }
        public int AssigneeUserID { get; set; }
        public int ClientID { get; set; }
        public string Notes { get; set; }
        public bool IsClosed { get; set; }
        public bool IsRead { get; set; }
        public bool IsNotified { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
