//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cashier
    {
        public Cashier()
        {
            this.LedgerAccounts = new HashSet<LedgerAccount>();
        }
    
        public int CashierID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<LedgerAccount> LedgerAccounts { get; set; }
    }
}
