//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.LedgerAccounts = new HashSet<LedgerAccount>();
            this.Reservations = new HashSet<Reservation>();
            this.Tickets = new HashSet<Ticket>();
            this.ClientGroups = new HashSet<ClientGroup>();
        }
    
        public int ClientID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Address { get; set; }
        public string CellPhone1 { get; set; }
        public string CellPhone2 { get; set; }
        public string HomePhone { get; set; }
        public string OfficePhone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public int CreationUserID { get; set; }
        public int BranchID { get; set; }
        public string ProfilePictureName { get; set; }
        public string FullName { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<LedgerAccount> LedgerAccounts { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual ICollection<ClientGroup> ClientGroups { get; set; }
    }
}
