//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightReservation
    {
        public int ReservationID { get; set; }
        public string TicketNo { get; set; }
        public string RefSystem { get; set; }
        public string RefAirLine { get; set; }
        public string FromLocation { get; set; }
        public string ToLocation { get; set; }
        public string AirLine { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
