//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelReservation
    {
        public int ReservationID { get; set; }
        public string HotelName { get; set; }
        public string Location { get; set; }
        public int SingleRooms { get; set; }
        public int DoubleRooms { get; set; }
        public int TripleRooms { get; set; }
        public int QuadRooms { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
