//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LedgerTransactionDetail
    {
        public int LedgerTransactionDetailsID { get; set; }
        public int LedgerTransactionID { get; set; }
        public decimal Amount { get; set; }
        public int LedgerTransactionTypeID { get; set; }
        public int LedgerAccountID { get; set; }
    
        public virtual LedgerAccount LedgerAccount { get; set; }
        public virtual LedgerTransaction LedgerTransaction { get; set; }
        public virtual LedgerTransactionType LedgerTransactionType { get; set; }
    }
}
