//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LedgerAccount
    {
        public LedgerAccount()
        {
            this.FinantialTransactions = new HashSet<FinantialTransaction>();
            this.FinantialTransactions1 = new HashSet<FinantialTransaction>();
            this.LedgerTransactionDetails = new HashSet<LedgerTransactionDetail>();
        }
    
        public int LedgerAccountID { get; set; }
        public int GeneralLedgerAccountID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> CashierID { get; set; }
        public Nullable<int> BankAccountID { get; set; }
        public Nullable<int> ExpenseID { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual Cashier Cashier { get; set; }
        public virtual Client Client { get; set; }
        public virtual Expens Expens { get; set; }
        public virtual ICollection<FinantialTransaction> FinantialTransactions { get; set; }
        public virtual ICollection<FinantialTransaction> FinantialTransactions1 { get; set; }
        public virtual GeneralLedgerAccount GeneralLedgerAccount { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<LedgerTransactionDetail> LedgerTransactionDetails { get; set; }
    }
}
