//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentType
    {
        public PaymentType()
        {
            this.FinantialTransactions = new HashSet<FinantialTransaction>();
        }
    
        public int PaymentTypeID { get; set; }
        public string Name { get; set; }
        public bool IsBankOperation { get; set; }
    
        public virtual ICollection<FinantialTransaction> FinantialTransactions { get; set; }
    }
}
