//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public Reservation()
        {
            this.LedgerTransactions = new HashSet<LedgerTransaction>();
            this.ReservationClients = new HashSet<ReservationClient>();
        }
    
        public int ReservationID { get; set; }
        public int ClientID { get; set; }
        public int CreationUserID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int TypeID { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public int StatusID { get; set; }
        public int VendorID { get; set; }
        public decimal BasicPrice { get; set; }
        public decimal Taxes { get; set; }
        public decimal CommitionRatio { get; set; }
        public decimal NetPrice { get; set; }
        public decimal Commission { get; set; }
        public string Note { get; set; }
        public decimal PaidAmount { get; set; }
        public Nullable<decimal> BalanceDue { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual FlightReservation FlightReservation { get; set; }
        public virtual HotelReservation HotelReservation { get; set; }
        public virtual ICollection<LedgerTransaction> LedgerTransactions { get; set; }
        public virtual ICollection<ReservationClient> ReservationClients { get; set; }
        public virtual ReservationStatus ReservationStatus { get; set; }
        public virtual ReservationType ReservationType { get; set; }
        public virtual User User { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual VisaReservation VisaReservation { get; set; }
    }
}
