//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Clients = new HashSet<Client>();
            this.FinantialTransactions = new HashSet<FinantialTransaction>();
            this.Notes = new HashSet<Note>();
            this.Reservations = new HashSet<Reservation>();
            this.Vendors = new HashSet<Vendor>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int GroupID { get; set; }
        public bool isActive { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
        public virtual ICollection<FinantialTransaction> FinantialTransactions { get; set; }
        public virtual ICollection<Note> Notes { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual UserGroup UserGroup { get; set; }
        public virtual ICollection<Vendor> Vendors { get; set; }
    }
}
