//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisaReservation
    {
        public int ReservationID { get; set; }
        public string Country { get; set; }
        public string VisaType { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
